version: "3.9"
services:
  db:
    image: postgres:17
    container_name: chatapp_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
