spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatapp
    username: chatuser
    password: chatpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
