spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}

