spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/chatapp
    username: chatuser
    password: chatpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  error:
    include-message: always

jwt:
  secret: 029DObcj44vaBTbx1PrSsFW0CbbdKefq6gLJGKY7meQ=

